# Site settings
author: nhinhdao
title: Robin vs Ruby 
header-img: img/home-bg.png
email: nhinhdao.vn@gmail.com
copyright_name: nhinhdao
description: > # this means to ignore newlines until "baseurl:"
  Coding issues, thoughts and solutions of a Rubyist
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nhinhdao

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
