# Site settings
author: drobin
title: Robin vs Ruby 
header-img: img/home-header.jpg
email: robin.frvn@gmail.com
copyright_name: drobin
description: > # this means to ignore newlines until "baseurl:"
  Coding issues, thoughts and solutions of a code lover <3
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: _drobin_
github_username:  nhinhdao

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
